[build]
builder = "NIXPACKS"
buildCommand = "cd game && npm install && npm run build"

[deploy]
startCommand = "cd game && node bin/server/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
PORT = "${{RAILWAY_PUBLIC_PORT}}" 